2024-11-27 10:23:33 [twisted] CRITICAL: Unhandled error in Deferred:
2024-11-27 10:23:33 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 2017, in _inlineCallbacks
    result = context.run(gen.send, result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/crawler.py", line 152, in crawl
    self.engine = self._create_engine()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/crawler.py", line 166, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/core/engine.py", line 102, in __init__
    self.scraper: Scraper = Scraper(crawler)
                            ^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/core/scraper.py", line 101, in __init__
    self.itemproc: ItemPipelineManager = itemproc_cls.from_crawler(crawler)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/middleware.py", line 77, in from_crawler
    return cls._from_settings(crawler.settings, crawler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/middleware.py", line 86, in _from_settings
    mwcls = load_object(clspath)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/misc.py", line 71, in load_object
    mod = import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 8, in <module>
    from itemadapter import ItemAdapz
ImportError: cannot import name 'ItemAdapz' from 'itemadapter' (/home/gellar/opt/pyvenv/lib/python3.12/site-packages/itemadapter/__init__.py). Did you mean: 'ItemAdapter'?
2024-11-27 10:36:41 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责游戏中gameplay各模块的设计与开发，根据需求制定合理技术方案并实现；\r\n'
          '2.负责游戏中相关模块的工具扩展与工具链建设，参与规范制定、性能优化等工作；\r\n'
          '3.参与引擎特性开发和技术预研，根据需求定制引擎功能；\r\n'
          '4.负责游戏中相关问题的跟进与解决。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1765020202073858048'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 30, in process_item
    self.sh1.append(item["post_id"],
TypeError: Worksheet.append() takes 2 positional arguments but 7 were given
2024-11-27 10:36:41 [scrapy.core.scraper] ERROR: Error processing {'about': '1.建设财付通资金账务核算平台系统能力；\r\n'
          '2.负责财付通账务核算平台、备付金监管报送平台研发建设，落实备付金监管合规要求，保障财付通内外部资金安全与流动性。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1797551910631251968'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 30, in process_item
    self.sh1.append(item["post_id"],
TypeError: Worksheet.append() takes 2 positional arguments but 7 were given
2024-11-27 10:36:41 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责云环境的渗透测试和漏洞挖掘，包括对云平台、云服务和云基础设施进行安全评估；\n'
          '2.跟踪和了解最新的云安全威胁和攻防技术，保持团队对云安全领域的技术更新；\n'
          '3.参与云产品漏洞的修复和漏洞管理过程，与开发团队合作解决安全问题；\n'
          '4.参与内外部安全演练，验证业务安全水位。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1819022572327563264'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 30, in process_item
    self.sh1.append(item["post_id"],
TypeError: Worksheet.append() takes 2 positional arguments but 7 were given
2024-11-27 10:36:41 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责线上游戏技术发展规划及新游戏客户端技术评估，确保技术发展满足项目运营需求，技术筹备有序推进；\r\n'
          '2.负责客户端、产能研效相关方向具体优化方案定制输出，优化各项目技术品质体验。并推进方案在业务中应用，对落地效果负责；\r\n'
          '3.负责调研各项目组需求，驱动内部研发及外部支持资源，帮助业务解决各类研发与发行技术问题，提高研发与发行的技术效率和质量；\r\n'
          '4.关注前沿游戏技术动向和政策法规，帮助新技术和政策法规在游戏中应用落地。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '五年以上工作经验',
 'location': '深圳',
 'post_id': '1764955445274877952'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 30, in process_item
    self.sh1.append(item["post_id"],
TypeError: Worksheet.append() takes 2 positional arguments but 7 were given
2024-11-27 10:36:41 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责大规模在线服务的架构设计、开发和维护；\r\n'
          '2.高效地完成登录、好友、战队等系统的开发、测试和运维发布的工作；\r\n'
          '3.分析服务器性能瓶颈，针对性能瓶颈进行有效优化；\r\n'
          '4.建立完善的监控和分析系统，保证业务高质量运行，并及时响应各种突发事件。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '五年以上工作经验',
 'location': '深圳',
 'post_id': '1765020270038360064'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 30, in process_item
    self.sh1.append(item["post_id"],
TypeError: Worksheet.append() takes 2 positional arguments but 7 were given
2024-11-27 10:36:41 [scrapy.core.scraper] ERROR: Error processing {'about': '1.设计、开发和优化机器学习模型，应用于微信小店及微信交易的内容审核、风险控制、商家行为监管和用户安全等治理场景；\n'
          '2.基于海量的数据，进行数据清洗、特征提取、模型训练和评估，提升平台违规行为检测的准确性和效率；\n'
          '3.参与反作弊、信息过滤、虚假交易检测等关键系统的算法研发和优化，维护平台生态健康。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '一年以上工作经验',
 'location': '广州',
 'post_id': '1836335098966859776'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 30, in process_item
    self.sh1.append(item["post_id"],
TypeError: Worksheet.append() takes 2 positional arguments but 7 were given
2024-11-27 10:36:41 [scrapy.core.scraper] ERROR: Error processing {'about': '1.参与微信搜索大模型预训练应用研究，致力于在提升利用大模型的技术，在业务场景上提升内容理解，语义检索，相关性匹配等核心线条的效果，应用业务场景例如通用搜索、视频搜索、搜索推荐等；\r\n'
          '2.提升整个大模型预训练的能力，包括不限于数据质量、配比，以及合成数据，模型结构调优，以及上下文学习、SFT、搜索增强等技术点。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '北京',
 'post_id': '1819367703459160064'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 30, in process_item
    self.sh1.append(item["post_id"],
TypeError: Worksheet.append() takes 2 positional arguments but 7 were given
2024-11-27 10:36:41 [scrapy.core.scraper] ERROR: Error processing {'about': '1.参与微信输入法核心功能设计、开发及维护，包括但不限于服务性能调优、技术难点攻坚、指标自动化监控、异构大模型调度等；\n'
          '2.参与维护后台服务，保证线上稳定性，以及搭建自动化分析系统，提升工程效率；\n'
          '3.参与新技术调研以及探索，以及项目特定方向的重点、难点开发工作。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '两年以上工作经验',
 'location': '北京',
 'post_id': '1699632287001354240'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 30, in process_item
    self.sh1.append(item["post_id"],
TypeError: Worksheet.append() takes 2 positional arguments but 7 were given
2024-11-27 10:36:41 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责为云上客户提供红队评估服务，提升客户业务安全性；\r\n'
          '2.负责内部安全演练，验证腾讯云安全防御水位，促进平台安全建设；\r\n'
          '3.跟踪日常安全动态，开展前沿攻防技术研究。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '西安',
 'post_id': '1807617298291236864'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 30, in process_item
    self.sh1.append(item["post_id"],
TypeError: Worksheet.append() takes 2 positional arguments but 7 were given
2024-11-27 10:36:41 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责下列一项或多项工作；\r\n'
          '2.游戏的性能优化工作，针对需求制定游戏的各个规格规范，负责图形兼容性分析以及疑难问题的分析定位工作，开发对应的工具，帮助研发团队提升研发效率；\r\n'
          '3.游戏动画特性开发，根据需求开发高级动画效果，增强游戏表现力；\r\n'
          '4.针对需求定制增改UE引擎底层功能，开发引擎相关特性（光照、渲染、管线、资源管理等）；\r\n'
          '5.针对最新的Feature进行研究分析，优化性能和表现效果，保证在游戏中实际落地；\r\n'
          '6.调研业界的最新技术，与美术TA一起合作完成高级图形效果开发。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1797532513753636864'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 30, in process_item
    self.sh1.append(item["post_id"],
TypeError: Worksheet.append() takes 2 positional arguments but 7 were given
2024-11-27 13:22:46 [scrapy.core.scraper] ERROR: Error processing {'about': '1.参与AIGC应用产品App的需求分析、需求评估和应用架构设计；\r\n'
          '2.参与AIGC应用产品App的相关业务模块的开发与运维；\r\n'
          '3.负责解决产品开发工作中的复杂问题，提升产品稳定性和性能。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1832038080257744896'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:22:46 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责腾讯混元相关内外部产品的web前端开发工作；\r\n'
          '2.要对负责的产品的服务稳定性、兼容性、体验等提供保障；\r\n'
          '3.从开发、调试、部署等一系列流程上，保证效率以及质量。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1839239899392274432'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:22:46 [scrapy.core.scraper] ERROR: Error processing {'about': '1.参与AIGC应用产品App的需求分析、需求评估和应用架构设计；\r\n'
          '2.参与AIGC应用产品App的相关业务模块的开发与运维；\r\n'
          '3.负责解决产品开发工作中的复杂问题，提升产品稳定性和性能。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1767145961072631808'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:22:46 [scrapy.core.scraper] ERROR: Error processing {'about': '1.参与搜索排序算法优化工作，通过技术优化，提升搜索体验；\r\n'
          '2.工作内容包括并不限于：用户需求理解、相关性优化、质量权威性优化、召回和精排优化、case 问题分析等；\r\n'
          '3.涉及技术包括并不限于：大模型应用、海量用户行为挖掘、高级特征建设、深度模型调优等。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '一年以上工作经验',
 'location': '北京',
 'post_id': '1829103287970848768'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:22:46 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责微信游戏社区内容推荐、精品游戏推荐及小游戏推荐系统算法研发相关工作；通过算法提升游戏分发效率及优化内容推荐的消费、时长、留存等指标；\r\n'
          '2.参与推荐系统召回和排序等各环节算法迭代；深入理解游戏用户数据，从样本、特征、模型等维度不断优化排序算法；\r\n'
          '3.紧跟学术界、工业界的前沿技术，结合实际的业务场景进行算法开发、落地，实现团队技术和业务的共同发展。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '两年以上工作经验',
 'location': '深圳',
 'post_id': '1859161568827170816'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:22:46 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责企业微信核心业务板块后端分布式数据库架构设计和工程落地；\r\n'
          '2.负责数据库核心模块(如底层存储引擎、复杂公式、查询优化器/执行器等)持续迭代和优化；\r\n'
          '3.对现有业务架构进行分析和优化，保障系统的高性能、可靠性以及可扩展性。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '五年以上工作经验',
 'location': '成都',
 'post_id': '1852382083230490624'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:22:46 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责企业微信核心业务板块后端分布式数据库架构设计和工程落地；\r\n'
          '2.负责数据库核心模块(如底层存储引擎、复杂公式、查询优化器/执行器等)持续迭代和优化；\r\n'
          '3.对现有业务架构进行分析和优化，保障系统的高性能、可靠性以及可扩展性。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '五年以上工作经验',
 'location': '广州',
 'post_id': '1852382086573355008'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:22:46 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责企业微信邮箱和微盘本地版后台开发维护工作；\n'
          '2.深入参与企业微信邮箱和微盘本地版功能迭代需求研发，持续优化系统，维持系统稳定。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '广州',
 'post_id': '1853670714826055680'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:22:46 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责应用宝业务质量保障相关工作，包含整体质量体系规划和质量方案设计；\n'
          '2.负责质量数据分析及质量复盘等质量问题分析诊断等工作；\n'
          '3.负责功能、性能、兼容性、接口测试等专项测试；\n'
          '4.对测试外包进行良好的体系化、专业化管理及培养能力提升，把控测试结果并持续提升测试质量；\n'
          '5.对测试过程实施自动化改进提升测试效率，行业优秀质量保障实践的引入和落地，持续提升整体交付质量。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '五年以上工作经验',
 'location': '深圳',
 'post_id': '1843845549611053056'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:22:46 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责QQ、浏览器业务质量保障相关工作，包含整体质量体系规划和质量方案设计；\n'
          '2.负责质量数据分析及质量复盘等质量问题分析诊断等工作；\n'
          '3.负责功能、性能、兼容性、接口测试等专项测试；\n'
          '4.对测试外包进行良好的体系化、专业化管理及培养能力提升，把控测试结果并持续提升测试质量；\n'
          '5.对测试过程实施自动化改进提升测试效率，行业优秀质量保障实践的引入和落地，持续提升整体交付质量。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '五年以上工作经验',
 'location': '深圳',
 'post_id': '1843845547245461504'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:23:38 [scrapy.core.scraper] ERROR: Error processing {'about': '1.参与AIGC应用产品App的需求分析、需求评估和应用架构设计；\r\n'
          '2.参与AIGC应用产品App的相关业务模块的开发与运维；\r\n'
          '3.负责解决产品开发工作中的复杂问题，提升产品稳定性和性能。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1832038080257744896'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:23:38 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责腾讯混元相关内外部产品的web前端开发工作；\r\n'
          '2.要对负责的产品的服务稳定性、兼容性、体验等提供保障；\r\n'
          '3.从开发、调试、部署等一系列流程上，保证效率以及质量。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1839239899392274432'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:23:38 [scrapy.core.scraper] ERROR: Error processing {'about': '1.参与AIGC应用产品App的需求分析、需求评估和应用架构设计；\r\n'
          '2.参与AIGC应用产品App的相关业务模块的开发与运维；\r\n'
          '3.负责解决产品开发工作中的复杂问题，提升产品稳定性和性能。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1767145961072631808'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:23:38 [scrapy.core.scraper] ERROR: Error processing {'about': '1.参与搜索排序算法优化工作，通过技术优化，提升搜索体验；\r\n'
          '2.工作内容包括并不限于：用户需求理解、相关性优化、质量权威性优化、召回和精排优化、case 问题分析等；\r\n'
          '3.涉及技术包括并不限于：大模型应用、海量用户行为挖掘、高级特征建设、深度模型调优等。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '一年以上工作经验',
 'location': '北京',
 'post_id': '1829103287970848768'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:23:38 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责微信游戏社区内容推荐、精品游戏推荐及小游戏推荐系统算法研发相关工作；通过算法提升游戏分发效率及优化内容推荐的消费、时长、留存等指标；\r\n'
          '2.参与推荐系统召回和排序等各环节算法迭代；深入理解游戏用户数据，从样本、特征、模型等维度不断优化排序算法；\r\n'
          '3.紧跟学术界、工业界的前沿技术，结合实际的业务场景进行算法开发、落地，实现团队技术和业务的共同发展。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '两年以上工作经验',
 'location': '深圳',
 'post_id': '1859161568827170816'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:23:38 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责企业微信核心业务板块后端分布式数据库架构设计和工程落地；\r\n'
          '2.负责数据库核心模块(如底层存储引擎、复杂公式、查询优化器/执行器等)持续迭代和优化；\r\n'
          '3.对现有业务架构进行分析和优化，保障系统的高性能、可靠性以及可扩展性。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '五年以上工作经验',
 'location': '成都',
 'post_id': '1852382083230490624'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:23:38 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责企业微信核心业务板块后端分布式数据库架构设计和工程落地；\r\n'
          '2.负责数据库核心模块(如底层存储引擎、复杂公式、查询优化器/执行器等)持续迭代和优化；\r\n'
          '3.对现有业务架构进行分析和优化，保障系统的高性能、可靠性以及可扩展性。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '五年以上工作经验',
 'location': '广州',
 'post_id': '1852382086573355008'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:23:38 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责企业微信邮箱和微盘本地版后台开发维护工作；\n'
          '2.深入参与企业微信邮箱和微盘本地版功能迭代需求研发，持续优化系统，维持系统稳定。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '三年以上工作经验',
 'location': '广州',
 'post_id': '1853670714826055680'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:23:38 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责应用宝业务质量保障相关工作，包含整体质量体系规划和质量方案设计；\n'
          '2.负责质量数据分析及质量复盘等质量问题分析诊断等工作；\n'
          '3.负责功能、性能、兼容性、接口测试等专项测试；\n'
          '4.对测试外包进行良好的体系化、专业化管理及培养能力提升，把控测试结果并持续提升测试质量；\n'
          '5.对测试过程实施自动化改进提升测试效率，行业优秀质量保障实践的引入和落地，持续提升整体交付质量。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '五年以上工作经验',
 'location': '深圳',
 'post_id': '1843845549611053056'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-27 13:23:38 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责QQ、浏览器业务质量保障相关工作，包含整体质量体系规划和质量方案设计；\n'
          '2.负责质量数据分析及质量复盘等质量问题分析诊断等工作；\n'
          '3.负责功能、性能、兼容性、接口测试等专项测试；\n'
          '4.对测试外包进行良好的体系化、专业化管理及培养能力提升，把控测试结果并持续提升测试质量；\n'
          '5.对测试过程实施自动化改进提升测试效率，行业优秀质量保障实践的引入和落地，持续提升整体交付质量。',
 'country': '中国',
 'date': '2024年11月27日',
 'least_work_year': '五年以上工作经验',
 'location': '深圳',
 'post_id': '1843845547245461504'}
Traceback (most recent call last):
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 65, in process_item
    self.cur.execute(sql)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'post_id' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 70, in process_item
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1
2024-11-28 09:48:02 [scrapy.core.scraper] ERROR: Error processing {'about': '1.与项目团队紧密合作，为游戏产品提供专业、先进的技术解决方案，支撑丰富的游戏产品内容，提升游戏品质；\r\n'
          '2.参与或主导构建健壮、灵活、实用的游戏后台解决方案，改进后台服务性能和研发效率 ；\r\n'
          '3.不断学习探索业界容器化、cloud native 和微服务等理念，结合游戏业务场景，构建云原生游戏后台解决方案。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1765195827854188544'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:02 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责AI Lab语音技术团队音乐基础技术，尤其是基于AIGC算法的基础研究和应用落地；\r\n'
          '2.侧重于研发音乐生成、音乐理解、数据管线、音频生成与理解的基础算法；\r\n'
          '3.通过跟踪和创新，确保算法方面的行业领先，通过打造技术PAAS平台服务于腾讯内部各个业务场景包括游戏、社交、内容服务、广告、金融、车载助手、企业服务（如腾讯会议、企业微信、企点客服、商通、数智人）等等，帮助业务产生实际价值和打造业界领先的语音应用产品；\r\n'
          '4.持续关注学术界和行业的最新研究动态，参与国际会议、研讨会，与全球顶级团队进行交流合作。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1830499361826562048'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:02 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责腾讯大数据OLAP系统内核研发及相关生态建设，直接参与建设腾讯多个核心产品线的OLAP平台体系；\r\n'
          '2.负责超大规模下的MPP计算引擎、搜索分析引擎、存算分离等技术的研发工作，打造业界领先的PB级OLAP系统；\r\n'
          '3.负责分析系统瓶颈与架构合理性，促进服务架构优化，参与开源社区的合作。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '八年以上工作经验',
 'location': '深圳',
 'post_id': '1797900695035191296'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:02 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责腾讯自研分布式数据库TDSQL研发工作；\n'
          '2.负责计算引擎的设计和开发，包括整体框架、执行算子、表达式计算、CPU执行效率等层面的开发及优化工作；\n'
          '3.负责存储引擎的设计和开发，包括但不限于行存储、列存储、分布式事务、高可用等方向的开发及优化工作；\n'
          '4.负责内核相关的稳定性/可用性优化、性能调优等工作。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1797896606792556544'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:02 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责大模型安全相关问题的研究，包括但不限于大模型的数据安全，隐私安全，服务安全，安全攻防对抗等方面；\r\n'
          '2.负责跟进大模型安全相关的前沿技术进展，探索在公司落地；\r\n'
          '3.协助跟进大模型在安全领域的最新进展，并探索落地应用。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1699629724503908352'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:02 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责突发终端App/OS安全事件的应急分析和处置能力，包括但不限于逆向分析、去混淆、脱壳等；\r\n'
          '2.负责终端安全漏洞、安全加固、安全 SDK 等关键安全系统的设计开发和运营，重点是移动App(Android/iOS)；\r\n'
          '3.持续跟踪和调研行业最新技术，不断提升终端安全防护能力的水位，保持行业领先。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1710476505231925248'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:02 [scrapy.core.scraper] ERROR: Error processing {'about': '1.通过对AIGC大模型（3D生成）的研究优化，提升模型的生成质量、速度、多样性、可控性；\r\n'
          '2.推动3D生成模型工业化部署和产品落地。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1808701309486899200'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:02 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责UE4或UE5引擎客户端的底层模块开发以及优化；；\r\n'
          '2.根据游戏玩法进行技术选型，对项目核心架构进行搭建与后续功能的开发，对领域前沿保持跟进，针对需求做出最优选择；；\r\n'
          '3.负责跟进优化迭代当前的生产管线，能够主动发现问题并针对管线和玩法内容优化框架结构，提升效能；；\r\n'
          '4.分析并解决性能问题，优化引擎客户端以及DedicatedServer的性能和内存。。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '五年以上工作经验',
 'location': '成都',
 'post_id': '1678373590686244864'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:02 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责微信客户端小游戏框架开发工作，包括性能调优、技术难点攻坚等；\r\n'
          '2.持续优化游戏性能，提高用户体验和使用效率；\r\n'
          '3.负责新技术框架的探索。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '一年以上工作经验',
 'location': '广州',
 'post_id': '1808428931502579712'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:02 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责大世界图形引擎相关技术方案的设计与实现；\n'
          '2.负责图形引擎在不同平台的的性能优化和效果适配；\n'
          '3.协助美术/TA同学优化开发工具和流程。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1810887460436058112'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:54 [scrapy.core.scraper] ERROR: Error processing {'about': '1.与项目团队紧密合作，为游戏产品提供专业、先进的技术解决方案，支撑丰富的游戏产品内容，提升游戏品质；\r\n'
          '2.参与或主导构建健壮、灵活、实用的游戏后台解决方案，改进后台服务性能和研发效率 ；\r\n'
          '3.不断学习探索业界容器化、cloud native 和微服务等理念，结合游戏业务场景，构建云原生游戏后台解决方案。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1765195827854188544'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:54 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责AI Lab语音技术团队音乐基础技术，尤其是基于AIGC算法的基础研究和应用落地；\r\n'
          '2.侧重于研发音乐生成、音乐理解、数据管线、音频生成与理解的基础算法；\r\n'
          '3.通过跟踪和创新，确保算法方面的行业领先，通过打造技术PAAS平台服务于腾讯内部各个业务场景包括游戏、社交、内容服务、广告、金融、车载助手、企业服务（如腾讯会议、企业微信、企点客服、商通、数智人）等等，帮助业务产生实际价值和打造业界领先的语音应用产品；\r\n'
          '4.持续关注学术界和行业的最新研究动态，参与国际会议、研讨会，与全球顶级团队进行交流合作。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1830499361826562048'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:54 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责腾讯大数据OLAP系统内核研发及相关生态建设，直接参与建设腾讯多个核心产品线的OLAP平台体系；\r\n'
          '2.负责超大规模下的MPP计算引擎、搜索分析引擎、存算分离等技术的研发工作，打造业界领先的PB级OLAP系统；\r\n'
          '3.负责分析系统瓶颈与架构合理性，促进服务架构优化，参与开源社区的合作。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '八年以上工作经验',
 'location': '深圳',
 'post_id': '1797900695035191296'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:54 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责腾讯自研分布式数据库TDSQL研发工作；\n'
          '2.负责计算引擎的设计和开发，包括整体框架、执行算子、表达式计算、CPU执行效率等层面的开发及优化工作；\n'
          '3.负责存储引擎的设计和开发，包括但不限于行存储、列存储、分布式事务、高可用等方向的开发及优化工作；\n'
          '4.负责内核相关的稳定性/可用性优化、性能调优等工作。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1797896606792556544'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:54 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责大模型安全相关问题的研究，包括但不限于大模型的数据安全，隐私安全，服务安全，安全攻防对抗等方面；\r\n'
          '2.负责跟进大模型安全相关的前沿技术进展，探索在公司落地；\r\n'
          '3.协助跟进大模型在安全领域的最新进展，并探索落地应用。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1699629724503908352'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:54 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责突发终端App/OS安全事件的应急分析和处置能力，包括但不限于逆向分析、去混淆、脱壳等；\r\n'
          '2.负责终端安全漏洞、安全加固、安全 SDK 等关键安全系统的设计开发和运营，重点是移动App(Android/iOS)；\r\n'
          '3.持续跟踪和调研行业最新技术，不断提升终端安全防护能力的水位，保持行业领先。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1710476505231925248'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:54 [scrapy.core.scraper] ERROR: Error processing {'about': '1.通过对AIGC大模型（3D生成）的研究优化，提升模型的生成质量、速度、多样性、可控性；\r\n'
          '2.推动3D生成模型工业化部署和产品落地。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1808701309486899200'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:54 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责UE4或UE5引擎客户端的底层模块开发以及优化；；\r\n'
          '2.根据游戏玩法进行技术选型，对项目核心架构进行搭建与后续功能的开发，对领域前沿保持跟进，针对需求做出最优选择；；\r\n'
          '3.负责跟进优化迭代当前的生产管线，能够主动发现问题并针对管线和玩法内容优化框架结构，提升效能；；\r\n'
          '4.分析并解决性能问题，优化引擎客户端以及DedicatedServer的性能和内存。。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '五年以上工作经验',
 'location': '成都',
 'post_id': '1678373590686244864'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:54 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责微信客户端小游戏框架开发工作，包括性能调优、技术难点攻坚等；\r\n'
          '2.持续优化游戏性能，提高用户体验和使用效率；\r\n'
          '3.负责新技术框架的探索。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '一年以上工作经验',
 'location': '广州',
 'post_id': '1808428931502579712'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 09:48:54 [scrapy.core.scraper] ERROR: Error processing {'about': '1.负责大世界图形引擎相关技术方案的设计与实现；\n'
          '2.负责图形引擎在不同平台的的性能优化和效果适配；\n'
          '3.协助美术/TA同学优化开发工具和流程。',
 'country': '中国',
 'date': '2024年11月28日',
 'least_work_year': '三年以上工作经验',
 'location': '深圳',
 'post_id': '1810887460436058112'}
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/defer.py", line 390, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/Desktop/program/python/xiaoetong/crawler/scrapy16-21/scrapy18/onclass/onclass/pipelines.py", line 58, in process_item
    sql = 'INSERT INTO tencent VALUES(NULL, "%s", "%s", "%s", "%s", "%s")' % (
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
2024-11-28 10:27:38 [twisted] CRITICAL: Unhandled error in Deferred:
2024-11-28 10:27:38 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/misc.py", line 74, in load_object
    obj = getattr(mod, name)
          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'onclass.pipelines' has no attribute 'OnclassExcelPipline'. Did you mean: 'OnclassExcelPipeline'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/twisted/internet/defer.py", line 2017, in _inlineCallbacks
    result = context.run(gen.send, result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/crawler.py", line 152, in crawl
    self.engine = self._create_engine()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/crawler.py", line 166, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/core/engine.py", line 102, in __init__
    self.scraper: Scraper = Scraper(crawler)
                            ^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/core/scraper.py", line 101, in __init__
    self.itemproc: ItemPipelineManager = itemproc_cls.from_crawler(crawler)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/middleware.py", line 77, in from_crawler
    return cls._from_settings(crawler.settings, crawler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/middleware.py", line 86, in _from_settings
    mwcls = load_object(clspath)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/gellar/opt/pyvenv/lib/python3.12/site-packages/scrapy/utils/misc.py", line 76, in load_object
    raise NameError(f"Module '{module}' doesn't define any object named '{name}'")
NameError: Module 'onclass.pipelines' doesn't define any object named 'OnclassExcelPipline'
